chan_pjsip: Test Session Timer
asterisk/testsuite pull request #18
Opened 2023-08-28 06:20 UTC by btriller

Test if chan_pjsip replies w/ 422 (Session Interval Too Small) response to an INVITE request w/ Session-Expires lower than timers_min_se setting.

2023-08-28 06:29 UTC, btriller commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-30 10:38 UTC, jcolp approved these changes

2023-09-22 14:05 UTC, gtjoseph requested changes
You need to squash and remove the merge commit.

2023-09-22 14:26 UTC, gtjoseph approved these changes

2023-09-22 15:19 UTC, merged