Update wiki links
asterisk/testsuite pull request #19
Opened 2023-08-28 06:24 UTC by btriller

2023-08-28 06:29 UTC, btriller commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-28 08:28 UTC, jcolp approved these changes

2023-09-22 13:56 UTC, gtjoseph requested changes
Can you squash and get rid of the merge commit?

2023-09-22 14:24 UTC, gtjoseph approved these changes

2023-09-22 15:19 UTC, merged