dial_progress: Fix originate and improve test robustness.
asterisk/testsuite pull request #69
Opened 2024-10-16 21:44 UTC by InterLinked1

* Fix originate to extension '0' instead of 's' as in dialplan.
* Eliminate the Fail UserEvent if we continue past the pass dials. Previously, the test suite would initiate shutdown as soon as 2 passes were received, which caused the answer dial channel allocation to fail, leading dialplan execution to continue onwards to stuff it wasn't supposed to execute in a successful test, triggering a failure. To test the same scenario, explicitly continue onwards and check DIALSTATUS for an additional pass, which should prevent us from getting shut down before the test has concluded.

2024-10-16 21:44 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-10-16 21:45 UTC, InterLinked1 commented
This test doesn't actually pass currently (and thus should NOT be merged as is), but I'm looking for insight as to why that is.

2024-10-17 14:01 UTC, gtjoseph commented
> This test doesn't actually pass currently (and thus should NOT be merged as is), but I'm looking for insight as to why that is.

@InterLinked1 Have you been able to test it locally?  Pass or fail?
Did the logs tell you anything?  If yo uhaven't already, you can get them from...
https://github.com/asterisk/asterisk/actions/runs/11375404767?pr=949
and scrolling down to Artifacts, then downloading the one for [app_dial-master](https://github.com/asterisk/asterisk/actions/runs/11375404767/artifacts/2066288363)

2024-10-17 20:45 UTC, InterLinked1 commented
> > This test doesn't actually pass currently (and thus should NOT be merged as is), but I'm looking for insight as to why that is.
> 
> @InterLinked1 Have you been able to test it locally? Pass or fail? Did the logs tell you anything? If yo uhaven't already, you can get them from... https://github.com/asterisk/asterisk/actions/runs/11375404767?pr=949 and scrolling down to Artifacts, then downloading the one for [app_dial-master](https://github.com/asterisk/asterisk/actions/runs/11375404767/artifacts/2066288363)

Yeah, it's like I was saying in the other thread. I was running it locally extensively yesterday. The test fails, because for some reason it starts shutting down prematurely while dialplan is still running - even if it hasn't hit the target number of Passes yet. I can't figure out why that's happening, just that it is from the logs. I'm wondering if you have any insight on that or if it happens for you.

2024-10-17 22:17 UTC, gtjoseph requested changes

2024-10-17 22:17 UTC, gtjoseph commented on tests/apps/dial/dial_progress/configs/ast1/extensions.conf
> +	same => n,Dial(Local/s@answer,3^2,,g) ; call will answer, and will continue
You have 2 commas so the `g` isn't being picked up as an option which means the call won't continue to the next priority after hangup.

2024-10-17 22:17 UTC, gtjoseph commented on tests/apps/dial/dial_progress/test-config.yaml
> +            count: 3
First, get rid of the hangup monitor stuff.  It's not helping.

Second, setting `count: 3` doesn't actually cause the test case to wait for 3 occurrences.  You want to do something like...
```
ami-config:
    -
        ami-events:
            conditions:
                match:
                    Event: 'UserEvent'
                    UserEvent: 'DialProgress'
            requirements:
                match:
                    Result: 'Pass'
            count: 3
    -
        ami-events:
            conditions:
                match:
                    Event: 'Hangup'
                    Channel: 'Local/s@default-00000000;1'
            count: 1
        stop_test:
```

Now the test will stop on the final Hangup and will then check that there were 3 occurrences of the UserEvent.

When I fixed the test up locally, it took 10 seconds and passed.

2024-10-17 22:24 UTC, InterLinked1 commented
Thanks for catching those! Completely missed the extra comma, I guess I was too confident about that...

2024-10-18 13:33 UTC, gtjoseph commented
> Also curious, given the test shouldn't have passed previously, do you know why the CI wasn't flagging it as failing?

The apps tests aren't normally run as part of the PR testing process because they take too long.  They only run during the Nightly tests which, admittedly, I don't look at often enough. 
 I disabled it as soon as I saw it failing regularly.

2024-10-18 13:35 UTC, gtjoseph requested changes
You should also remove the `hangup-monitor` config section.

2024-10-18 15:20 UTC, gtjoseph requested changes

2024-10-18 15:20 UTC, gtjoseph commented on tests/apps/dial/dial_progress/test-config.yaml
> +        stop-test:
Typo:  It's `stop_test` not `stop-test`.

2024-10-18 17:07 UTC, InterLinked1 commented
> You should also remove the `hangup-monitor` config section.

Isn't that this section here? https://github.com/asterisk/testsuite/pull/69/files/cea65bf26bb0b65dabe8569ea035ae9c68cb3a93#diff-d8934754b72f2f2c5f4857aae10fdb71d49de059a4cc5ac6d17ec9b81add17dcL15

2024-10-18 17:30 UTC, gtjoseph commented
> Hmm, does that mean even if we specify `testsuite-pr`, if it's an app test, it won't actually get run as part of the change? Or is that an exception to this rule?

It's not an exception.  Specifying `testsuite-pr` just tells the script to check out that PR. The script isn't smart enough to determine what actual test the files in the PR are part of.  Maybe in the future.

> I'm also curious if breaking up the non-run tests like apps into chunks would allow us to run them all in a reasonable amount of time. I'm running 30 different workflows in my Asterisk builds now and they all seem to run in parallel just fine.

We already run 11 parallel jobs per branch so for a 4 branch cherry-pick test, that's 44 parallel jobs, each requiring GitHub to spin up a VM.  I just added apps/dial so this PR could get tested.  The more we add, the greater chance that GitHub is just going to queue them behind other workloads.  It's also an issue for the private forks we use for security issues.  Private repos only get 3000 job-minutes per month so we either have to pay for more or stop testing.

2024-10-18 17:33 UTC, gtjoseph commented
As for hangup-monitor...  You removed the reference to the python module but not the actual config section down below on lines 29 and 30.  Stupidly, GitHub doesn't allow you to add review comments to lines that weren't changed so I can't select them.

2024-10-18 17:37 UTC, gtjoseph commented
Oh...   There's a new feature you can use to include tests that may not be run automatically.
Add a symlink to the test directory in the tests/extra_tests directory and add an entry to tests/extra_tests/tests.yaml.  Anything in extra_tests will automatically get run for all PR tests.  @bford used it for tenant_id.

2024-10-18 18:55 UTC, gtjoseph approved these changes

2024-10-23 09:43 UTC, jcolp approved these changes

2024-10-24 13:17 UTC, merged