pcap: Make yappcap optional
asterisk/testsuite pull request #71
Opened 2024-10-21 16:29 UTC by mbradeen

Move starpy into requirements.txt and make extras.txt optional.

This makes yappcap optional.  As individual tests check for it anyway, it's
failure should not force the test suite venv install to fail.

The pjsip rls tests had a python lib dependency on yappcap that wasn't really
required.  Resolved by splitting pcap.py into pcap_proxy.py where the latter
has no yappcap dependency.

Fixes: #70

2024-10-21 16:29 UTC, mbradeen commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-10-22 13:46 UTC, gtjoseph requested changes

2024-10-22 13:46 UTC, gtjoseph commented on setupVenv.sh
> +	python3 -m pip install -r ./extras.txt || true
I'd add a message here that states that some requirements failed.  Maybe something like...
```
python3 -m pip install -r ./extras.txt || {
    echo "**************************" >&2
    echo "Some optional python requirements failed to install.  The following tests may not run:" >&2
    grep -lEr "python\s*:\s*[']?yappcap" tests >&2
    echo "**************************" >&2
}
```

2024-10-22 13:46 UTC, gtjoseph commented
You should also cherry-pick to the two cert branches.

2024-10-22 17:51 UTC, mbradeen commented on setupVenv.sh
> +	python3 -m pip install -r ./extras.txt || true
changed

2024-10-23 12:45 UTC, gtjoseph approved these changes

2024-10-24 15:13 UTC, merged